/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index.js";
import * as YourClientNameTesting from "../../../index.js";
import * as core from "../../../../core/index.js";

export class MovieDoesNotExistError extends errors.YourClientNameTestingError {
    constructor(body: YourClientNameTesting.MovieId, rawResponse?: core.RawResponse) {
        super({
            message: "MovieDoesNotExistError",
            statusCode: 404,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, MovieDoesNotExistError.prototype);
    }
}
