"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DevinApiTimeoutError = void 0;
class DevinApiTimeoutError extends Error {
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, DevinApiTimeoutError.prototype);
    }
}
exports.DevinApiTimeoutError = DevinApiTimeoutError;
