/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "./core/index.mjs";
import { mergeHeaders } from "./core/headers.mjs";
import { Imdb } from "./api/resources/imdb/client/Client.mjs";
export class DevinApiClient {
    constructor(_options) {
        this._options = Object.assign(Object.assign({}, _options), { headers: mergeHeaders({
                "X-Fern-Language": "JavaScript",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
            }, _options === null || _options === void 0 ? void 0 : _options.headers) });
    }
    get imdb() {
        var _a;
        return ((_a = this._imdb) !== null && _a !== void 0 ? _a : (this._imdb = new Imdb(this._options)));
    }
}
