/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevinApi from "../../../index.mjs";
export interface Movie {
    id: DevinApi.MovieId;
    title: string;
    /** The rating scale out of ten stars */
    rating: number;
}
