/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core/index.mjs";
import * as DevinApi from "../../../index.mjs";
export declare namespace Imdb {
    interface Options {
        environment: core.Supplier<string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}
export declare class Imdb {
    protected readonly _options: Imdb.Options;
    constructor(_options: Imdb.Options);
    /**
     * Add a movie to the database
     *
     * @param {DevinApi.CreateMovieRequest} request
     * @param {Imdb.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.imdb.createMovie({
     *         title: "title",
     *         rating: 1.1
     *     })
     */
    createMovie(request: DevinApi.CreateMovieRequest, requestOptions?: Imdb.RequestOptions): core.HttpResponsePromise<DevinApi.MovieId>;
    private __createMovie;
    /**
     * Retrieve a movie from the database based on the ID
     *
     * @param {DevinApi.MovieId} id
     * @param {Imdb.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link DevinApi.MovieDoesNotExistError}
     *
     * @example
     *     await client.imdb.getMovie("tt0111161")
     *
     * @example
     *     await client.imdb.getMovie("tt1234")
     */
    getMovie(id: DevinApi.MovieId, requestOptions?: Imdb.RequestOptions): core.HttpResponsePromise<DevinApi.Movie>;
    private __getMovie;
}
