/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors/index.mjs";
export class MovieDoesNotExistError extends errors.DevinApiError {
    constructor(body, rawResponse) {
        super({
            message: "MovieDoesNotExistError",
            statusCode: 404,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, MovieDoesNotExistError.prototype);
    }
}
