/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors/index.mjs";
import * as DevinApi from "../../../index.mjs";
import * as core from "../../../../core/index.mjs";
export declare class MovieDoesNotExistError extends errors.DevinApiError {
    constructor(body: DevinApi.MovieId, rawResponse?: core.RawResponse);
}
